# Generated by Django 3.0.7 on 2021-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('amount', models.CharField(max_length=10)),
                ('coins_balance', models.CharField(max_length=10)),
                ('txn_type', models.CharField(max_length=10)),
                ('txn_info', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=13)),
            ],
        ),
    ]
